### PR TITLE
Adding product schema

### PR DESCRIPTION
**Pull request by jodiedoubleday**
#### What does this PR do?
- Adds product schema to a product tile.
- This PR assumes a tile will always be associated with a product, for now that is true. In the future it may not.

#### What unit or integration tests does this PR have?
- Adds a test for title

#### What selenium tests does this PR have?
N/A

#### How should a developer review this?
Go to http://schema.org/Product and look at the example product schema
Ensure the same process is followed on this element

#### How should this be manually tested?
One you have checked out the branch
`npm install`
`npm run build-dev`
and open `dev/index.html` to view the component
run the resulting html through https://developers.google.com/structured-data/testing-tool/ and ensure it passes the test

#### Any background context you want to provide?
UI components must work for everyone, therefore SEO and Schema are important.

#### What are the relevant tickets?
None yet

#### What gif best describes how you feel about this work?
tile fall

---
#### Quality checklist (for PR author to complete BEFORE code review):
- [x] I've checked there is appropriate unit test coverage.
- [x] I've checked there is appropriate selenium test coverage.
- [x] I've included regression tests for any bug fixes.
- [x] I've updated documentation with any changes to procedures.
- [x] I've tested this on mobile Android, Safari, Chrome for any visual changes.
- [x] I've tested this on desktop IE9/10/11, Firefox, Chrome for any visual changes.
- [x] I've checked any significant visual changes with a member of the UX/UI pod.
- [x] I've checked this work against the requirements of the Jira.
- [x] I've added and updated translations for all supported languages
- [x] I've informed those who need to know of any unforeseen impact of this work (database migrations, deployment procedure changes).
- [x] I am ready for this to be code reviewed, merged and tested.
- [x] I've thought about writing a blog post about this

#### IP or Developer Review:
- [x] I agree with the assumptions made in the quality checklist.
- [x] I’ve witnessed the work behaving as expected.
- [x] I’ve run all the tests locally and they pass.
- [x] +1 from me!

#### Software Engineer or Developer review:
- [x] I agree with the assumptions made in the quality checklist.
- [x] I’ve witnessed the work behaving as expected.
- [x] I’ve run all the tests locally and they pass.
- [x] I’ve checked for appropriate test coverage.
- [x] I’ve checked for coding anti-patterns.
- [x] I've checked this work against the requirements of the Jira.
- [x] +1 from me!

#### Software Engineer or project guru review:
- [x] I agree with the assumptions made in the quality checklist.
- [x] I’ve witnessed the work behaving as expected.
- [x] I’ve run all the tests locally and they pass.
- [x] I’ve checked for appropriate test coverage.
- [x] I’ve checked for coding anti-patterns.
- [x] I don’t believe this work introduces unnecessary technical debt.
- [x] +1 from me!

### CODE REVIEW

**Comment by jackdcrawford** [comment]
Taking SE/Dev

**Comment by jackdcrawford** [comment]
This looks good, would be cool if the test asserted that these scheme attributes exist on the elements when rendered?

**Comment by dancork** [comment]
Taking IP/dev

**Comment by dancork** [comment]
This is cool :+1:

**Comment by shackpank** [comment]
On SE/Guru

**Comment by shackpank** [comment]
similar comment about test, but that the thing with `itemprop=name` has text content "Shoes", rather than that the first h4 has that attribute - the second isn't making the right guarantees and seems prone to breaking on unrelated changes

**Pull request merged**
